---
- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: true
  
- name: "Remove unrequired dependencies"
  become: true
  apt:
    autoremove: true
  

- name: "Install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
      
- name: "install pm2"
  become: true
  apt:
    name: pm2
    state: present
    production: true
    global: yes
